services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./api/models:/app/models
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - api

  mlflow:
    image: python:3.10-slim
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_data:/mlflow
    working_dir: /mlflow
    command: >
      bash -c "pip install mlflow &&
               mlflow server --host 0.0.0.0 --port 5000
               --backend-store-uri sqlite:///mlflow/mlflow.db
               --default-artifact-root /mlflow/artifacts"

  airflow:
    image: apache/airflow:2.9.1
    container_name: airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/data
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname A --lastname B --role Admin --email admin@example.com || true &&
               airflow scheduler & airflow webserver"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning/dashboards

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml